server:
  port: 8098
  servlet:
    context-path: /
  tomcat:
    accept-count: 500
    max-http-form-post-size: 5
    threads:
      min-spare: 50
      max: 800
    uri-encoding: UTF-8
    connection-timeout: 5000ms
#    context-path: /cc



spring:
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,classpath:/templates
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
#    static-path-pattern: /zz/**
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.10.10.146:3306/mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 11
    minIdle: 17
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  servlet:
    multipart:
      max-file-size: 10Mb
      file-size-threshold: 5Mb
      location: D://temp
  redis:
    client-name: redis-one
    database: 0
    host: 10.10.10.146
    port: 6379
    lettuce:
      pool:
        max-active: 30
        max-wait: 3ms
        min-idle: 1
        max-idle: 10
#    redis集群配置
#    cluster:
#      max-redirects: 2
#      nodes:
#        - 10.10.10.146:6379
#        - localhost:6379


logging:
  level:
    root: info
    com.ssm.springmvc.controller: info

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
        exclude: auditevents
      base-path: /cc
  #      path-mapping:
  #        health: /hea
  server:
    address: 127.0.0.1
    servlet:
      context-path: /manage
    port: 8097
  endpoint:
    caches:
      cache:
        time-to-live: 10s
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    environment: mysql
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:config/mapper-config.xml
#  type-aliases-package: com.ssm.springmvc.db.entity